version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=sandbox_db
      - NEXT_PUBLIC_KEYCLOAK_URL=http://keycloak:8180/auth
      - NEXTAUTH_SECRET="af724fd6895ff6780c1c0ff842de470360544e588fc9344e92865c8de94a9743"
      - NEXTAUTH_URL="http://localhost:3000"
      - KEYCLOAK_CLIENT_ID="roster-client"
      - KEYCLOAK_CLIENT_SECRET="8wP6kV1B6jYBOVjhGlWGOjPJD0n39JOG"
      - KEYCLOAK_ISSUER_URL="http://localhost:8180/auth/realms/RosterManagement"

    depends_on:
      - postgres
      - keycloak
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sandbox_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=sandbox_db
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - "8180:8080"
    restart: unless-stopped

volumes:
  pgdata:
